"""initial schema

Revision ID: 2469080936c5
Revises: 
Create Date: 2026-07-01 12:25:27.502015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2469080936c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'WORKER', 'VETERINARIAN', 'FINANCE', 'READ_ONLY', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_farm_id'), 'app_user', ['farm_id'], unique=False)
    op.create_table('feed_item',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_item_farm_id'), 'feed_item', ['farm_id'], unique=False)
    op.create_table('herd',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herd_farm_id'), 'herd', ['farm_id'], unique=False)
    op.create_table('knowledge_object',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.String(length=100), nullable=False),
    sa.Column('pattern_version', sa.String(length=20), nullable=False),
    sa.Column('supporting_observation_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'SUPERSEDED', name='knowledge_object_status'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_object_entity_id'), 'knowledge_object', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_object_farm_id'), 'knowledge_object', ['farm_id'], unique=False)
    op.create_table('location',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_farm_id'), 'location', ['farm_id'], unique=False)
    op.create_table('animal',
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('species', sa.Enum('COW', 'SHEEP', 'GOAT', 'HORSE', name='animal_species'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'ACTIVE', 'UNDER_OBSERVATION', 'IN_TREATMENT', 'WITHDRAWAL_PERIOD', 'PREGNANT', 'SOLD', 'DECEASED', name='animal_status'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_farm_id'), 'animal', ['farm_id'], unique=False)
    op.create_index(op.f('ix_animal_tag_number'), 'animal', ['tag_number'], unique=False)
    op.create_table('feed_lot',
    sa.Column('feed_item_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('PURCHASE', 'PRODUCTION', name='lot_source'), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_lot_farm_id'), 'feed_lot', ['farm_id'], unique=False)
    op.create_table('flock',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('CHICKEN', 'DUCK', 'TURKEY', name='flock_species'), nullable=False),
    sa.Column('bird_count', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flock_farm_id'), 'flock', ['farm_id'], unique=False)
    op.create_table('observation',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('observation_type', sa.String(length=100), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.Enum('A_INSTRUMENT', 'B_COUNTED', 'C_HUMAN_OBSERVED', 'D_OPINION', name='observation_quality'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observer_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VALID', 'FLAGGED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrects_observation_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['corrects_observation_id'], ['observation.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_entity_id'), 'observation', ['entity_id'], unique=False)
    op.create_index(op.f('ix_observation_entity_type'), 'observation', ['entity_type'], unique=False)
    op.create_index(op.f('ix_observation_farm_id'), 'observation', ['farm_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_object_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('HEALTH', 'PRODUCTION', 'INVENTORY', 'FINANCIAL', 'BREEDING', 'COMPLIANCE', name='recommendation_category'), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='recommendation_priority'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_band'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('explanation_provider', sa.String(length=30), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACCEPTED', 'REJECTED', 'MONITORING', 'ACTION_IN_PROGRESS', 'CLOSED', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['knowledge_object_id'], ['knowledge_object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_entity_id'), 'recommendation', ['entity_id'], unique=False)
    op.create_index(op.f('ix_recommendation_farm_id'), 'recommendation', ['farm_id'], unique=False)
    op.create_table('decision',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'REJECT', 'MONITOR', 'DELEGATE', 'ESCALATE', 'POSTPONE', name='decision_option'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delegated_to', sa.UUID(), nullable=True),
    sa.Column('postponed_until', sa.Date(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['delegated_to'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_farm_id'), 'decision', ['farm_id'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_id'), 'decision', ['recommendation_id'], unique=False)
    op.create_table('egg_collection',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('total_eggs', sa.Integer(), nullable=False),
    sa.Column('broken_eggs', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('hatching', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['flock_id'], ['flock.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egg_collection_farm_id'), 'egg_collection', ['farm_id'], unique=False)
    op.create_index(op.f('ix_egg_collection_flock_id'), 'egg_collection', ['flock_id'], unique=False)
    op.create_table('feed_distribution',
    sa.Column('feed_lot_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['feed_lot_id'], ['feed_lot.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_distribution_farm_id'), 'feed_distribution', ['farm_id'], unique=False)
    op.create_table('herd_animal',
    sa.Column('herd_id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['herd_id'], ['herd.id'], ),
    sa.PrimaryKeyConstraint('herd_id', 'animal_id')
    )
    op.create_table('milk_record',
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('session', sa.Enum('AM', 'PM', name='milk_session'), nullable=False),
    sa.Column('volume_liters', sa.Float(), nullable=False),
    sa.Column('quality_abnormal', sa.Boolean(), nullable=False),
    sa.Column('destination', sa.Enum('SALE', 'PROCESSING', 'CONSUMPTION', 'WASTE', name='milk_destination'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_record_animal_id'), 'milk_record', ['animal_id'], unique=False)
    op.create_index(op.f('ix_milk_record_farm_id'), 'milk_record', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milk_record_farm_id'), table_name='milk_record')
    op.drop_index(op.f('ix_milk_record_animal_id'), table_name='milk_record')
    op.drop_table('milk_record')
    op.drop_table('herd_animal')
    op.drop_index(op.f('ix_feed_distribution_farm_id'), table_name='feed_distribution')
    op.drop_table('feed_distribution')
    op.drop_index(op.f('ix_egg_collection_flock_id'), table_name='egg_collection')
    op.drop_index(op.f('ix_egg_collection_farm_id'), table_name='egg_collection')
    op.drop_table('egg_collection')
    op.drop_index(op.f('ix_decision_recommendation_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_farm_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_recommendation_farm_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_entity_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_observation_farm_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_entity_type'), table_name='observation')
    op.drop_index(op.f('ix_observation_entity_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_flock_farm_id'), table_name='flock')
    op.drop_table('flock')
    op.drop_index(op.f('ix_feed_lot_farm_id'), table_name='feed_lot')
    op.drop_table('feed_lot')
    op.drop_index(op.f('ix_animal_tag_number'), table_name='animal')
    op.drop_index(op.f('ix_animal_farm_id'), table_name='animal')
    op.drop_table('animal')
    op.drop_index(op.f('ix_location_farm_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_knowledge_object_farm_id'), table_name='knowledge_object')
    op.drop_index(op.f('ix_knowledge_object_entity_id'), table_name='knowledge_object')
    op.drop_table('knowledge_object')
    op.drop_index(op.f('ix_herd_farm_id'), table_name='herd')
    op.drop_table('herd')
    op.drop_index(op.f('ix_feed_item_farm_id'), table_name='feed_item')
    op.drop_table('feed_item')
    op.drop_index(op.f('ix_app_user_farm_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('farm')
    # ### end Alembic commands ###
